langage: node_js
before_install:
  - chmod +x .travis/push.sh
before_script:
  - npm install
script:
  - npm run build:silent
  - npm run docs
cache:
  directories:
    - "node_modules"

after_success:
  - .travis/push.sh

env:
  global:
    secure: "kn7MFtoh5QdrNv0I2XPhDW+J+vP04DhPSTB5xGryJ+e6tqg2gl9qBhgdj16amDcY6mJNo173FJNbL4vG05yHwTEi0h/GG4AKGLjG6Uq+nhT3iOQiW22WEer3tTq3t4C4xKbEZaIAG3gQhWaMb/U5FDBFjdXD609Mhq5PbRAl/oqCg+FPekE8A6ViqKdv5fkcxIYMjtP4qXE5yGZK43lrNL3droE+prIKPnh2xRAjvGM7NeGmJGTy9ugnIAmur0EHE2a3AQj4xOuMd+ixXVjZhufHG1kR1pLLqHe0rD7JVsE6w4EH1i0MHDgJVuImIJcA9sL1Lhp3YWz6pjE3/zhG+zuMVhFUqYXvTFV8EuK5QtBRguyil3nC3YE5x2q0KaW4HFDXz1941y/Hh0yyfcaAzliZCjPd/HRoYMtPj0S79/Wqv4W15nsXVHpDOqV7HcG9lPdceNIUIe0WO4aO+ukbVDhdUsQ0rxciWPcI3cCaG8gyMbpGiiFRiTvLyqI7qx5ZXURIkD/lRqvcOoWu/FqMRfqQffOXkXsqI4msbFebScWchzknejPqeiRQ1DHkA7zPEVkakok1uRF9kfoPAw5ega215V3sJ/6sXwBpcgFdPMkj9xLJaO1irtXRpnpeCN6UdTv/ZV/l5CA2tI/Y7Pe+A8o60lv/hN6XvxFgE1D1+v0="